# Generated by Django 4.2.7 on 2023-11-23 22:03

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_remove_comentario_creador_alter_comentario_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=django_ckeditor_5.fields.CKEditor5Field('Ingredientes', config_name='extends'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='instrucciones',
            field=django_ckeditor_5.fields.CKEditor5Field('Instrucciones', config_name='extends'),
        ),
    ]
