"""
Django settings for proyecto project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from urllib.parse import urlsplit
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = os.path.join(BASE_DIR, "static")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Render siempre usa configuración de producción. Para otro proveedor, usar
# DJANGO_ENV=production. La depuración solo se habilita explícitamente en local.
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
IS_PRODUCTION = bool(RENDER_EXTERNAL_HOSTNAME) or os.environ.get('DJANGO_ENV') == 'production'
DEBUG = not IS_PRODUCTION and os.environ.get('DEBUG', '').lower() in {'1', 'true', 'yes'}
SECRET_KEY = os.environ.get('SECRET_KEY')
if IS_PRODUCTION and (not SECRET_KEY or SECRET_KEY.startswith('django-insecure-') or len(SECRET_KEY) < 50):
    raise ImproperlyConfigured('Configura una SECRET_KEY aleatoria de al menos 50 caracteres en producción.')
SECRET_KEY = SECRET_KEY or get_random_secret_key()
ALLOWED_HOSTS = [host.strip() for host in os.environ.get(
    'ALLOWED_HOSTS', '' if IS_PRODUCTION else 'localhost,127.0.0.1,[::1]'
).split(',') if host.strip()]
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
if IS_PRODUCTION and (not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS):
    raise ImproperlyConfigured('Configura hosts explícitos en ALLOWED_HOSTS.')
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_SSL_REDIRECT = IS_PRODUCTION
SECURE_HSTS_SECONDS = 3600 if IS_PRODUCTION else 0
if RENDER_EXTERNAL_HOSTNAME:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'aplicacion',
    'perfiles',
    'django_ckeditor_5',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'aplicacion/templates'
         ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600
    )
}

if IS_PRODUCTION and not os.environ.get('DATABASE_URL'):
    raise ImproperlyConfigured('Configura DATABASE_URL en producción.')
if DATABASES['default']['ENGINE'] == 'django.db.backends.mysql':
    DATABASES['default'].setdefault('OPTIONS', {}).setdefault('ssl', {})



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



MEDIA_URL = '/images/'
MEDIA_ROOT = os.path.join(BASE_DIR, "images/")

LOGIN_URL = 'login'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Cloudinary configuration para guardar imágenes en la nube
if 'CLOUDINARY_URL' in os.environ:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CKEDITOR_5_FILE_UPLOAD_PERMISSION = 'authenticated'
CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpg', 'jpeg', 'png', 'webp']
CKEDITOR_5_MAX_FILE_SIZE = 5

# Prefijos explícitos: solo el espacio de medios propio puede insertar imágenes.
HTML_IMAGE_URL_PREFIXES = [p.strip() for p in os.environ.get('HTML_IMAGE_URL_PREFIXES', '').split(',') if p.strip()]
if os.environ.get('CLOUDINARY_URL'):
    cloud_name = urlsplit(os.environ['CLOUDINARY_URL']).hostname
    if cloud_name:
        HTML_IMAGE_URL_PREFIXES.append(f'https://res.cloudinary.com/{cloud_name}/')

CKEDITOR_5_CONFIGS = {
    'default': {
        'language': 'es',
        'toolbar': ['bold', 'italic', 'link', 'bulletedList', 'numberedList'],
    },
    'extends': {
        'language': 'es',
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'bulletedList',
                    'numberedList', 'blockQuote', 'imageUpload'],
        'heading': {'options': [
            {'model': 'paragraph', 'title': 'Párrafo', 'class': 'ck-heading_paragraph'},
            {'model': 'heading2', 'view': 'h2', 'title': 'Título', 'class': 'ck-heading_heading2'},
            {'model': 'heading3', 'view': 'h3', 'title': 'Subtítulo', 'class': 'ck-heading_heading3'},
        ]},
        'image': {'toolbar': ['imageTextAlternative']},
    },
    'comentarios': {
        'language': 'es',
        'toolbar': ['bold', 'italic', 'link', 'bulletedList', 'numberedList'],
    },
}
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}']






# --- PARCHE PARA COMPATIBILIDAD CON PYTHON 3.14 (LOCAL) v2 ---
try:
    import django.template.context
    def _basecontext_copy(self):
        duplicate = object.__new__(self.__class__)
        duplicate.dicts = self.dicts[:]
        return duplicate
    django.template.context.BaseContext.__copy__ = _basecontext_copy
    def _context_copy(self):
        duplicate = object.__new__(self.__class__)
        duplicate.dicts = self.dicts[:]
        duplicate.render_context = django.template.context.copy(self.render_context) if hasattr(self, 'render_context') else None
        duplicate.template_name = getattr(self, 'template_name', None)
        for attr in ('request', 'autoescape', 'use_l10n', 'use_tz', 'template', '_processors', '_processors_index'):
            if hasattr(self, attr):
                setattr(duplicate, attr, getattr(self, attr))
        return duplicate
    django.template.context.Context.__copy__ = _context_copy
except Exception:
    pass
# -----------------------------------------------------------

